export const entitiesStrings = {
  mocks: {
      title: "Mocks",
      noMocksYet: "No mocks yet.\nClick  +  in the tab bar to create one.",
      noMocksOpen: "No mocks open",
      noMocksOpenHint: "Click a mock in the tree, or press + to create a new one.",
      newMock: "New Mock",
      editMock: "Edit Mock",
      searchPlaceholder: "Search mocks…",
      mockCount: "{count} mock{s}",
      mockCountActive: "{count} mock{s} · {active} active",
      importTitle: "Import mocks from Postman Collection JSON",
      exportTitle: "Export mocks as Postman Collection JSON",
      imported: "Imported {n} mock{s} · {f} folder{fs}",
      exported: "Exported {n} mock{s}",
      importFailed: "Import failed",
      exportFailed: "Export failed",
      urlTreeView: "URL tree view",
      folderView: "Folder view",
      collapseSidebar: "Collapse sidebar",
      expandSidebar: "Expand sidebar",
      expandAll: "Expand All",
      collapseAll: "Collapse All",
      openInTab: "Open in Tab",
      enable: "Enable",
      disable: "Disable",
      enableAll: "Enable All",
      disableAll: "Disable All",
      deleteAll: "Delete All ({n})",
      newTab: "New mock",
      closeTab: "Close tab",
      drafts: "Drafts",
      helpText: "Create HTTP mock endpoints that return fixed responses. Mocks intercept matching requests through the proxy before they reach real servers. Use {{VAR}} in URL patterns, response headers, and body to substitute environment variables.",
      mocksNote: "Mocks take priority over proxy rules and passthrough",
      addResponseBody: "Add a response body to save",
      saveMock: "Save Mock",
      importFromCurl: "Import from cURL",
      importFromCurlHint: "— paste a bash curl command to auto-fill method, URL, headers and body",
      mockName: "Mock name (optional)",
      urlPatternPlaceholder: "http://example.localhost/endpoint",
      curlPlaceholder: "curl -X POST http://example.localhost/endpoint \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"key\": \"value\"}'",
    },
  
    // Requests panel,

  requests: {
      title: "Requests",
      noRequestsYet: "No saved requests yet.\nClick  +  in the tab bar.",
      noRequestsOpen: "No requests open",
      noRequestsOpenHint: "Click a request in the tree, or press + to create a new one.",
      newRequest: "New Request",
      editRequest: "Edit Request",
      searchPlaceholder: "Search requests…",
      requestCount: "{count} request{s}",
      importTitle: "Import requests from Postman Collection JSON",
      exportTitle: "Export requests as Postman Collection JSON",
      imported: "Imported {n} request{s} · {f} folder{fs}",
      exported: "Exported {n} request{s}",
      importFailed: "Import failed",
      exportFailed: "Export failed",
      requestNamePlaceholder: "Request name (optional)",
      urlPlaceholder: "https://example.localhost/endpoint",
      importFromCurl: "Import from cURL",
      curlPlaceholder: "curl -X POST https://example.localhost/endpoint \\\n  -H 'Content-Type: application/json' \\\n  -d '{\"key\": \"value\"}'",
      createMock: "Create Mock",
      createMockTitle: "Create a mock pre-filled with this request + response",
      hitSendPrompt: "Hit Send to see the response",
      helpText: "Save and replay HTTP requests. Use the URL tree or folder view in the sidebar to browse saved requests. Paste a cURL command to auto-fill fields. After sending, use 'Create Mock' to instantly stub the response. Use {{VAR}} tokens in URL, headers, and body with an active environment.",
      newTab: "New request",
      closeTab: "Close",
      drafts: "Drafts",
      collectionFallback: "Collection",
    },
  
    // Capture panel,

  sockets: {
      helpText: "Open persistent WebSocket connections to local or remote servers. Save connections with URLs and headers for quick access. OutputStream shows sent messages; InputStream shows received messages. Use {{VAR}} tokens in URL and message body with an active environment. Max 5 live connections at any time.",
      newSocket: "New Socket",
      editSocket: "Edit Socket",
      namePlaceholder: "Socket name (optional)",
      connect: "Connect",
      disconnect: "Disconnect",
      maxConnectionsTitle: "Max {n} active connections",
      connectionsActive: "{n} connections active — disconnect another tab before connecting here.",
      outputStream: "OutputStream",
      noMessagesSent: "No messages sent yet",
      typeMessage: "Type a message…",
      connectToSend: "Connect to send messages",
      live: "Live",
      waiting: "Waiting",
      clear: "Clear",
      waitingForMessages: "Waiting for messages…",
      connectToReceive: "Connect to receive messages",
      saveSocket: "Save Socket",
      updateSocket: "Update Socket",
      searchPlaceholder: "Search sockets…",
      newTab: "New socket",
      noSocketsOpen: "No sockets open",
      noSocketsHintPrefix: "Click a socket in the tree, or press",
      noSocketsHintSuffix: "to create one.",
    },
  
    // Editor sections,

  webhooks: {
      title: "Webhooks",
      newWebhook: "New Webhook",
      webhook: "Webhook",
      namePlaceholder: "Webhook name (optional)",
      searchPlaceholder: "Search webhooks…",
      newTab: "New webhook",
      drafts: "Drafts",
      received: "Received",
      emptyBody: "(empty body)",
      empty: "(empty)",
      waitingForPost: "Waiting for POST requests…",
      activateToReceive: "Activate this webhook to receive payloads.",
      selectPayload: "Select a payload to view its body",
      openToReceive: "Open a webhook to start receiving POST requests",
      saveWebhook: "Save Webhook",
      updateWebhook: "Update Webhook",
      statusActive: "Active",
      statusAtLimit: "At limit",
      statusInactive: "Inactive",
      maxActive: "Max {n} webhooks active — close another tab to activate this one.",
      stopServer: "Stop webhook server",
      startServer: "Start webhook server",
      serverLabel: "Webhook server",
      serverStopped: "Webhook server stopped",
    },
  
    // Health bar panel,

  mappings: {
      title: "Localhost Mappings",
      subtitle: "Map *.localhost domains to local services",
      noMappingsYet: "No mappings yet",
      noMappingsYetHint: "Map a .localhost subdomain to a local service port.",
      noMatchingMappings: "No matching mappings",
      noMatchingMappingsHint: "Try a different search term.",
      addMapping: "+ Add Mapping",
      editMapping: "Edit Mapping",
      addMappingTitle: "Add Mapping",
      searchPlaceholder: "Domain, target…",
      columnDomain: "Domain",
      columnTarget: "Target",
      columnLabel: "Label",
      columnOn: "On",
      helpText: "Create subdomain mappings like example.localhost → 127.0.0.1:3000. Browsers resolve *.localhost to 127.0.0.1 automatically (RFC 6761) — no hosts file edits needed. The server must be running on port 80 for bare hostnames to work.",
      subdomainLabel: "Subdomain",
      subdomainPlaceholder: "example or client.example",
      localHostSuffix: ".localhost",
      willCreate: "Will create:",
      targetLabel: "Target (ip:port)",
      targetPlaceholder: "127.0.0.1:3000",
      labelLabel: "Label (optional)",
      labelPlaceholder: "My App",
      subdomainRequired: "Subdomain is required",
      subdomainInvalid: "Each label must contain only letters, numbers, hyphens (no leading/trailing hyphens)",
      subdomainDuplicate: "{domain} is already mapped",
      targetInvalid: "Enter a valid host:port (e.g. 127.0.0.1:3000)",
      exportTitle: "Export mappings to JSON",
      importTitle: "Import mappings from JSON",
      exported: "Exported {n} mapping{s}",
      exportFailed: "Export failed",
      imported: "Imported {n} mapping{s}",
      importFailed: "Import failed",
      publish: "Publish",
      revert: "Revert",
      viewHistory: "View history",
    },
  
    // Settings panel,

  proxyRules: {
      title: "Proxy Rules",
      subtitle: "Route, rewrite, and forward HTTP traffic to local mappings or external hosts",
      addRule: "Add Rule",
      columnName: "Name",
      columnPattern: "Match Pattern",
      columnTarget: "Target",
      columnScripts: "Scripts",
      noRulesYet: "No proxy rules yet",
      noRulesYetHint: "Create proxy rules to match URL patterns and redirect or rewrite traffic.",
      noMatchingRules: "No matching rules",
      noMatchingRulesHint: "Try adjusting your search terms.",
      editRule: "Edit Rule",
      newRuleTitle: "New Proxy Rule",
      detailsTitle: "Proxy Rule Details",
      helpText: "Proxy rules apply when Bifurc is configured as your system or browser HTTP proxy. Each rule matches a URL pattern and forwards matching requests to a mapped local service or external host. Rules are evaluated top-to-bottom — first match wins. Use request/response scripts to manipulate traffic.",
      exportTitle: "Export proxy rules to JSON",
      importTitle: "Import proxy rules from JSON",
      exported: "Exported {n} rule{s}",
      exportFailed: "Export failed",
      imported: "Imported {n} rule{s}",
      importFailed: "Import failed",
      newRule: "New Rule",
      newTab: "New rule",
      closeTab: "Close tab",
      drafts: "Drafts",
      noRulesOpen: "No rules open",
      searchPlaceholder: "Search rules…",
      collapseSidebar: "Collapse sidebar",
      expandSidebar: "Expand sidebar",
      saveRule: "Save Rule",
      ruleNamePlaceholder: "Rule name (optional)",
      targetMapping: "Mapped Service",
      targetExternal: "External Host",
      requestScript: "Request Script",
      responseScript: "Response Script",
      regexToggle: "Regex",
      exactToggle: "Exact",
      requestScriptPlaceholder: "// Runs before request is forwarded\n// lp.request.headers — mutable object\n// lp.request.body    — mutable string",
      responseScriptPlaceholder: "// Runs before response is returned\n// lp.response.headers — mutable object\n// lp.response.body    — mutable string",
      ruleLabel: "Proxy Rule",
      matchUrl: "Match URL",
      forwardTo: "Forward To",
      switchToExact: "Switch to exact match",
      switchToRegex: "Switch to regex match",
      regexHelp: "Tested as a JavaScript regex against the full request URL.",
      exactHelp: "Exact string match against the full request URL.",
      selectMapping: "— select a mapping —",
      noMappingsDefined: "No mappings defined. Add one in the Mappings panel.",
      updateRule: "Update Rule",
      patternRequired: "Pattern is required",
      invalidRegexPattern: "Invalid regex pattern",
      selectTargetMapping: "Select a target mapping",
      enterHostPort: "Enter a host:port or domain",
      deleteConfirm: "Delete this rule? This cannot be undone.",
      noRulesOpenHintPrefix: "Click a rule in the tree, or press",
      noRulesOpenHintSuffix: "to create a new one.",
      copySuffix: " (copy)",
      rulesCountTitle: "{count} rules",
    },
  
    // Environments panel,

  environments: {
      title: "Environments",
      helpText: "Environments hold named variable sets. Switch the active environment from the title bar dropdown. Use {{VAR_NAME}} syntax anywhere in request/mock URLs, headers, body, or response body — values are substituted at send/match time. Variables not found in the active env are left as-is.",
      exportTitle: "Export environments to JSON",
      importTitle: "Import environments from JSON",
      exported: "Exported {n} environment{s}",
      exportFailed: "Export failed",
      imported: "Imported {n} environment{s}",
      importFailed: "Import failed",
      environmentName: "Environment name",
      alwaysActive: "Always Active",
      setActive: "Set Active",
      active: "Active",
      viewHistory: "View history",
      noVariables: "No variables — click Add Variable below",
      addVariable: "Add Variable",
      newEnvironment: "New Environment",
      noEnvironments: "No environments yet",
      noEnvironmentsDesc: "Create environments to manage variable sets for different stages.",
      useVarPrefix: "Use",
      useVarSuffix: "syntax anywhere in your requests and mocks.",
    },
  
    // Sockets panel,
} as const;
