export const settingsGroupStrings = {
  settings: {
      title: "Settings",
      subtitle: "Server configuration and data management",
      helpText: "Configure the proxy server port, tray behavior, and export/import your mappings and rules. Mocks and requests are managed separately in their own panels.",
      serverPort: "Server Port",
      serverPortDesc: "Port the server listens on. Use {hint} in your browser.",
      minimizeToTray: "Minimize to Tray on Close",
      minimizeToTrayDesc: "Keep the app running in the system tray instead of quitting when the window is closed.",
      restartServer: "Restart Server",
      restartServerDesc: "Stop and restart the background proxy server on the configured port.",
      exportConfig: "Export All Data",
      exportConfigDesc: "Save all workspaces and their data to a JSON file.",
      importConfig: "Import All Data",
      importConfigDesc: "Restore all workspaces from a previously exported JSON file. Replaces everything.",
      exportBtn: "Export…",
      importBtn: "Import…",
      configImported: "Config imported.",
      port80Hint: "Port 80:",
      port80Example: "example.localhost",
      port80Desc: "— browsers resolve {domain} to 127.0.0.1 automatically (RFC 6761).",
      otherPortHint: "Other port:",
      otherPortDesc: "Use {domain} in the browser. No proxy setup needed.",
      proxyHint: "System/browser proxy:",
      proxyDesc: "Optionally set {addr} as your HTTP proxy. Proxy rules then apply to all HTTP traffic. HTTPS is a transparent TCP tunnel — not inspected.",
      sectionServer: "Server",
      sectionTls: "TLS Interception",
      sectionConfig: "Configuration",
      sectionAbout: "About",
      tlsEnabled: "Intercept HTTPS",
      tlsEnabledDesc: "When enabled, HTTPS requests are decrypted so mocks and proxy rules can match them. Requires a trusted CA certificate configured below.",
      tlsCaCert: "CA Certificate",
      tlsCaCertDesc: "PEM-encoded CA certificate used to sign per-host certificates.",
      tlsCaKey: "CA Private Key",
      tlsCaKeyDesc: "Private key for the CA certificate.",
      tlsImport: "Import…",
      tlsRemove: "Remove",
      tlsNotConfigured: "Not configured",
      tlsInstallHint: "Install the CA certificate in your browser or OS trust store to avoid HTTPS warnings.",
      tlsGenerate: "Generate with mkcert",
      tlsGenerating: "Generating…",
      tlsInstallCA: "Install in System",
      tlsInstalling: "Installing…",
      tlsInstallSuccess: "Installed",
      tlsInstallFailed: "Install failed",
      tlsExportCert: "Export Cert…",
      tlsManualInstall: "Manual install required — run in a terminal:",
      tlsGenerateHint: "Generate a new local CA cert using mkcert (10-year validity, stored in app data). Then install it so browsers trust your local HTTPS.",
      darkMode: "Theme",
      darkModeDesc: "Choose a colour theme for the application",
      version: "Version",
      author: "Author",
      authorName: "Harshal Kudale",
      github: "GitHub",
      githubUrl: "https://github.com/HarshalKudale",
      githubDisplay: "github.com/HarshalKudale",
      license: "License",
      licenseName: "Bifurc Community and Commercial License",
      appDesc: "Local development proxy & mock server",
      webhookServerPort: "Webhook Server Port",
      webhookServerPortDesc: "Port for the dedicated webhook HTTP server (default 9101). Start/stop from the Webhooks panel.",
      currentlyLabel: "Currently:",
      companionPort: "Companion Extension Port",
      companionPortDesc: "WebSocket port for the companion browser extension (default 9271). The extension connects here to send captured requests.",
      themeGroupDark: "Dark",
      themeGroupLight: "Light",
      httpsIntercepted: "HTTPS traffic is intercepted and decrypted — mocks and proxy rules apply.",
      httpsTunnel: "HTTPS is a transparent TCP tunnel — not inspected.",
      sectionAppearance: "Appearance",
      sidebarPanels: "Sidebar Panels",
      sidebarPanelsDesc: "Choose which panels are visible in the sidebar",
      sidebarPanelsShown: "{visibleCount} of {n} shown",
      alwaysVisible: "Always visible",
      starOnGitHub: "Star on GitHub",
      supportProject: "Support Project",
      checkForUpdates: "Check for Updates",
      checkingForUpdates: "Checking for updates…",
      updateAvailable: "Update available",
      updateAvailableDesc: "A new version of Bifurc ({version}) is available.",
      upToDate: "You're up to date",
      upToDateDesc: "Bifurc is running the latest version ({version}).",
      downloadUpdate: "Download Update",
      viewReleaseNotes: "Release Notes",
      updateCheckFailed: "Failed to check for updates",
    },
  
    // Services panel,

  services: {
      title: "Services",
      helpText: "Discovers processes listening on localhost ports. Click 'Map →' next to any service to quickly create a localhost mapping for it. Hit Refresh to re-scan for new services.",
      subtitle: "Processes currently listening on localhost ports",
      quickStartTitle: "Start here",
      quickStartBody: "The fastest path is: map one running service, open it through Bifurc, then capture or test traffic. If Bifurc is not on port 80, use {domain} or configure the browser extension/system proxy.",
      quickStepOne: "Step 1",
      quickStepOneTitle: "Create a mapping",
      quickStepOneHint: "Use the detected service on port {port} as your first route.",
      quickStepOneEmpty: "No running localhost services were detected yet. You can still create a mapping manually.",
      quickStepTwo: "Step 2",
      quickStepTwoTitle: "Send a request",
      quickStepTwoHint: "Use the REST client to verify the route and save a reusable request.",
      quickStepThree: "Step 3",
      quickStepThreeTitle: "Capture traffic",
      quickStepThreeHint: "Capture now starts live so you can see requests immediately.",
      routingModesTitle: "Routing tips",
      routingModesBody: "Port 80 gives the cleanest experience. Otherwise open {domain} directly or send traffic through Bifurc on 127.0.0.1:{port}.",
      routingModesTip: "Use Settings only when you need to change ports or enable HTTPS interception.",
      openMappings: "Open Mappings",
      openServerSettings: "Open Settings",
      searchPlaceholder: "Port, process…",
      refresh: "Refresh",
      colProcess: "Process",
      colAddress: "Address",
      colPort: "Port",
      colStatus: "Status",
      colMap: "Map",
      mapped: "Mapped",
      unmapped: "Unmapped",
      mapAction: "Map",
      pid: "PID {pid}",
      noMatching: "No matching services",
      noServices: "No services found",
      noMatchingHint: "Try a different search term.",
      noServicesHint: "No processes are listening on localhost ports.",
    },
  
    // Proxy rules panel,
} as const;
