export const commonStrings = {
  common: {
      save: "Save",
      cancel: "Cancel",
      delete: "Delete",
      close: "Close",
      edit: "Edit",
      add: "Add",
      import: "Import",
      export: "Export",
      addRow: "Add Row",
      addEntry: "Add Entry",
      format: "Format",
      noHeaders: "No headers",
      noHeadersAddRow: "No headers — click Add Entry",
      noHeadersCaptured: "No headers captured",
      noHeadersAddRowBelow: "No headers — click Add Entry below",
      emptyBody: "empty body",
      noResults: "No results.",
      key: "Key",
      value: "Value",
      sync: "Sync",
      syncing: "Syncing…",
      revert: "Revert",
      reverting: "Reverting…",
      syncTooltip: "Sync (commit & push)",
      revertTooltip: "Revert local changes to last synced version",
      noChangesToRevert: "No local changes to revert",
      noChangesToSync: "No local changes to sync",
    },
  
    // Server status,

  server: {
      running: "Server running on port {port} — access via {hint}",
      notRunning: "Server not running",
      error: "{error}. Kill the process using that port or change the port above, then restart the server.",
      restarting: "Restarting…",
      restart: "Restart",
      sending: "Sending…",
      send: "Send",
      saving: "Saving…",
      testing: "Testing…",
      test: "Test",
    },
  
    // Mocks panel,

  binary: {
      preview: "Preview",
      hex: "Hex",
      base64: "Base64",
      copyBase64: "Copy base64",
      upload: "Upload",
      dropFile: "Drop a file here or click Upload",
      noBinaryData: "No binary data",
      fileTooLarge: "File too large ({size}). Max: 1 MB",
    },

  history: {
      title: "{kind} History",
      kindRequest: "Request",
      kindMock: "Mock",
      kindSocket: "Socket",
      kindEnvironment: "Environment",
      kindMapping: "Mapping",
      kindRule: "Rule",
      kindEntity: "Entity",
      closeHistory: "Close history",
      commit: "commit{s}",
      loading: "Loading…",
      noHistory: "No history found for this file.",
      localActor: "local",
      loadingDiff: "Loading diff…",
      noSnapshot: "No snapshot available.",
      deletedPrior: "Deleted — prior state in git history.",
      createdNoPrior: "Created — no prior state.",
      noFieldChanges: "No field changes detected.",
      hideUnchanged: "Hide {n} unchanged",
      showUnchanged: "Show {n} unchanged",
    },
  
    // Import/export modal,
} as const;
