export const editorStrings = {
  editor: {
      request: "Request",
      response: "Response",
      headers: "Headers",
      body: "Body",
      preScript: "Pre Script",
      postScript: "Post Script",
      inputstream: "InputStream",
      outputstream: "OutputStream",
      readOnly: "read-only",
      status: "Status",
      replayRequest: "Replay Request",
      back: "Back",
      scriptPlaceholder: "// JavaScript — runs before the request is sent\n// Available: lp.request.url, lp.request.headers, lp.request.body\n//            lp.environment.get/set/unset\n//            await lp.sendRequest(requestId)  → { status, headers, body }",
      postScriptPlaceholder: "// JavaScript — runs after the response is received\n// Available: lp.response.status, lp.response.headers, lp.response.body, lp.response.json()\n//            lp.environment.get/set/unset\n//            await lp.sendRequest(requestId)  → { status, headers, body }",
      scriptError: "Script error",
      modeJson: "JSON",
      modeText: "Text",
      modeHtml: "HTML",
      modeXml: "XML",
      modeForm: "Form",
      modeMultipart: "Multipart",
      modeBinary: "Binary",
      modeImage: "Image",
      modeNone: "None",
      noBody: "No body",
      noFormFields: "No form fields",
      noMultipartFields: "No multipart fields",
      noFileSelected: "No file selected",
      browse: "Browse",
      addField: "Add field",
      colType: "Type",
      typeTextToggle: "T",
      typeFileToggle: "F",
      placeholderKey: "key",
      placeholderValue: "value",
      placeholderFieldName: "field name",
      fileTooLarge: "File too large ({size}). Max: 1 MB",
      failedToOpenFile: "Failed to open file",
      activeEnv: "Active env: {name}",
      variablesHeader: "{name} variables",
      emptyValue: "empty",
      insertRandomToken: "Insert random value token",
      randomizerTokens: "Randomizer tokens",
      insert: "Insert",
      ctxClose: "Close",
      ctxCloseOthers: "Close Others",
      ctxCloseAll: "Close All",
      ctxDuplicate: "Duplicate",
      params: "Params",
      tests: "Tests",
      script: "Script",
      results: "Results",
      console: "Console",
      pass: "PASS",
      fail: "FAIL",
      noTestResults: "No test results yet. Write tests and send the request.",
      noQueryParams: "No query params — add a row or type ?key=value in the URL",
      noRequestBodyCaptured: "No request body captured",
      requestBodyOptional: "Request body (optional)",
      delay: "Delay",
      ms: "ms",
      msPerChunk: "ms/chunk",
      streamNone: "No Stream",
      streamSse: "SSE",
      streamChunked: "Chunked",
      responseDelayTitle: "Response delay in milliseconds",
      streamingModeTitle: "Streaming mode",
      chunkDelayTitle: "Chunk delay in ms",
      responseStatusTitle: "Response status code",
      status200: "200  OK",
      status201: "201  Created",
      status204: "204  No Content",
      status301: "301  Moved Permanently",
      status302: "302  Found",
      status304: "304  Not Modified",
      status400: "400  Bad Request",
      status401: "401  Unauthorized",
      status403: "403  Forbidden",
      status404: "404  Not Found",
      status405: "405  Method Not Allowed",
      status409: "409  Conflict",
      status422: "422  Unprocessable Entity",
      status429: "429  Too Many Requests",
      status500: "500  Internal Server Error",
      status502: "502  Bad Gateway",
      status503: "503  Service Unavailable",
      matchUrlAsRegex: "Match URL as regular expression",
      invalidRegex: "Invalid regex",
      requestFailed: "Request failed",
      saveFailed: "Save failed",
      preScriptError: "Pre-script: {error}",
      postScriptError: "Post-script: {error}",
      saveRequest: "Save Request",
      updateRequest: "Update Request",
      updateMock: "Update Mock",
    },
  
    // Workspace panel,

  capture: {
      title: "Capture",
      helpText: "Capture live HTTP requests passing through the proxy. Click 'Mock' to create a mock pre-filled with the captured request/response. Click 'Open' to replay in the Requests panel. Pause to stop the live feed.",
      exportTitle: "Export captured requests as Postman collection",
      exported: "Exported {n} request{s}",
      exportFailed: "Export failed",
      // Toolbar
      start: "Start",
      pause: "Pause",
      clear: "Clear",
      mockAll: "Mock All",
      saveAll: "Save All",
      searchPlaceholder: "URL, method, host…",
      selectedCount: "{count} selected",
      // Empty states
      emptyTitle: "No captured requests",
      emptyPausedHint: "Click Start to begin capturing HTTP traffic.",
      emptyLiveHint: "HTTP traffic will appear here as requests pass through the app.",
      emptyNoMatch: "No entries match your filter.",
      // Columns
      colName: "Name",
      colMethod: "Method",
      colStatus: "Status",
      colType: "Type",
      colFulfilledBy: "Fulfilled By",
      colSize: "Size",
      colTime: "Time",
      selectAll: "Select all",
      // Type tabs
      typeAll: "All",
      typeXhr: "Fetch/XHR",
      typeDoc: "Doc",
      typeCss: "CSS",
      typeJs: "JS",
      typeFont: "Font",
      typeImg: "Img",
      typeMedia: "Media",
      typeOther: "Other",
      // Fulfilled-by labels
      fulfilledExternal: "External",
      fulfilledProxy: "Proxy",
      fulfilledMock: "Mock",
      fulfilledError: "Error",
      // Detail tabs
      tabHeaders: "Headers",
      tabPayload: "Payload",
      tabResponse: "Response",
      tabTiming: "Timing",
      detailRequestHeaders: "Request Headers",
      detailResponseHeaders: "Response Headers",
      timingStarted: "Started",
      timingDuration: "Duration",
      timingStatus: "Status",
      timingFulfilledBy: "Fulfilled By",
      timingSize: "Size",
      emptyBody: "empty body",
      noHeaders: "No headers",
      closeDetail: "Close details",
      // Context menu - single row
      ctxMock: "Mock this request",
      ctxOpen: "Open in Requests",
      ctxSave: "Save to requests",
      ctxBlock: "Block request",
      ctxUnblock: "Unblock request",
      ctxShare: "Share (as JSON file)",
      ctxDelete: "Delete",
      // Context menu - multiple rows
      ctxMockMany: "Mock these requests",
      ctxSaveMany: "Save these to requests",
      ctxBlockMany: "Block these requests",
      ctxUnblockMany: "Unblock these requests",
      ctxShareMany: "Share these (as JSON file)",
      ctxDeleteMany: "Delete selected",
      subtitle: "Captured requests — persisted across sessions · last {count} kept",
      blockedPrefix: "Blocked —",
      replayResult: "Replay Result",
      sendingRequest: "Sending request…",
      responseHeaderCount: "{count} response headers",
      requestFailed: "Request failed",
      requestBodyPlaceholder: "Request body (optional)",
      sendToSeeResponse: "Send the request to see the response",
      headerCount: "{count} headers",
      createMockResponseTitle: "Create mock pre-filled with this response",
      createMockRequestTitle: "Create mock from request (send first to auto-fill response)",
      mockThisResponse: "Mock this response",
    },
  
    // Mappings panel,
} as const;
