export const navigationStrings = {
  nav: {
      discovery: "Discovery",
      routing: "Routing",
      tools: "Workspace",
      config: "Global Config",
      services: "Services",
      mappings: "Mappings",
      proxyRules: "Proxy Rules",
      capture: "Capture",
      requests: "Requests",
      mocks: "Mocks",
      sockets: "Sockets",
      environments: "Environments",
      settings: "Settings",
    },
  
    // Title bar,

  titleBar: {
      appName: "Bifurc",
      collapseSidebar: "Collapse sidebar",
      expandSidebar: "Expand sidebar",
      switchEnvironment: "Switch environment",
      noEnvironment: "No Env",
      manageEnvironments: "Manage Environments…",
      environment: "Environment",
      noEnv: "No Environment",
      stopServer: "Stop server",
      startServer: "Start server",
      portInUse: "Port {port} in use",
      active: "Proxy on :{port}",
      stopped: "Proxy off :{port}",
      serverRunning: "Server running",
      switchWorkspace: "Switch workspace",
      createWorkspace: "Create Workspace",
      workspaces: "Workspaces",
    },
  
    // Common actions,

  footer: {
      syncing: "syncing",
      changesWaitingToPublish: "changes waiting to be published",
      changesNotYetCommitted: "changes not yet committed",
      publishing: "Publishing…",
      publish: "Publish",
      sync: "sync",
      local: "local",
      upToDate: "up to date",
      commitLocalChangesTitle: "Commit local changes (no remote configured)",
    },
  
    // Panel registry (sections & help),

  panels: {
      sectionRest: "REST",
      sectionGraphql: "GraphQL",
      sectionSoap: "SOAP",
      sectionGrpc: "gRPC",
      sectionWebsocket: "WebSocket",
      sectionWebhooks: "Webhooks",
      sectionRunConfigs: "Runner",
      sectionHealthBar: "Health Bar",
      sectionWorkspace: "Workspace",
      sectionAuditLog: "Audit Log",
      sectionMock: "Mock",
      sectionRequest: "Request",
      sectionApplications: "Applications",
      sectionApi: "API",
      sectionRealtime: "Realtime",
      requestsHelp: "Create and send HTTP, GraphQL, gRPC, and SOAP requests. Organize requests in folders and test APIs with environment variables.",
      mocksHelp: "Create HTTP, GraphQL, gRPC, and SOAP mocks that intercept requests and return simulated responses.",
      graphqlMockHelp: "Create GraphQL mock operations. Match incoming queries and mutations by operation name and return configured responses.",
      soapMockHelp: "Create SOAP mock services. Match incoming requests by SOAPAction header and return configured XML responses.",
      grpcMockHelp: "Create gRPC mock services. Run a local gRPC server that returns configured responses for matched methods.",
      graphqlRequestHelp: "Send GraphQL queries and mutations. Import schemas via introspection or SDL files for query generation.",
      soapRequestHelp: "Send SOAP requests. Import WSDL files to discover operations and auto-generate request envelopes.",
      grpcRequestHelp: "Make gRPC calls. Import .proto files or use server reflection to discover services and methods.",
      webhooksHelp: "Create and manage webhooks. Open a webhook in a tab to activate it and receive POST requests on the webhook server.",
      healthbarHelp: "Monitor health check endpoints for your services. Responses are fetched live from the main process.",
      auditHelp: "A complete history of every configuration change in this workspace.",
    },
  
    // Binary viewer,

  io: {
      cancelled: "Cancelled",
      importFailed: "Import failed",
      exportFailed: "Export failed",
    },
  
    // GraphQL tabs & panels,
} as const;
