export const sidebarStrings = {
  sidebar: {
      searchPlaceholderDefault: "Search…",
      searchPanels: "Search panels…",
      noPanelsFound: "No panels found",
      switchWorkspace: "Switch workspace",
      workspace: "Workspace",
      workspaceOptions: "Workspace options",
      workspaceSettings: "Workspace Settings",
      auditLog: "Audit Log",
      createWorkspace: "Create Workspace",
      workspaces: "Workspaces",
      renameWorkspace: "Rename workspace",
      deleteWorkspace: "Delete workspace",
      deleteWorkspacePrefix: "Delete",
      deleteWorkspaceSuffix: "? All data in this workspace will be permanently removed.",
      discardDraft: "Discard draft",
    },
  
    // Entity history sidebar,

  folderTree: {
      renameFolder: "Rename Folder",
      moveToFolder: "Move to Folder",
      slashRoot: "/ root",
      root: "root",
      expandAll: "Expand All",
      collapseAll: "Collapse All",
      newSubfolder: "New Subfolder",
      newTab: "New Tab",
      commitPushFolder: "Commit & Push Folder",
      enableAllInFolder: "Enable All in Folder",
      disableAllInFolder: "Disable All in Folder",
      deleteFolder: "Delete Folder",
      runCollection: "Run Collection",
      unblock: "Unblock",
      open: "Open",
      commitDelete: "Commit Delete",
      commitPush: "Commit & Push",
      restore: "Restore",
      discardChanges: "Discard Changes",
      disable: "Disable",
      enable: "Enable",
      duplicate: "Duplicate",
      history: "History",
      block: "Block",
      delete: "Delete",
      move: "Move",
      expand: "Expand",
      collapse: "Collapse",
      start: "Start",
      stop: "Stop",
      nItems: "{n} item{s}",
      nFolders: "{n} folder{s}",
      nSelected: "{n} selected",
      and: " and ",
      deleteConfirmTracked: "Delete {what}? The item will be removed locally. You can still restore it or commit the deletion later from the context menu.",
      deleteConfirmUntracked: "Delete {what}? This item has never been committed and will be permanently removed.",
      pendingDeletion: "Pending Deletion",
      pendingDeletionBody: "has been deleted locally but not yet committed. You can restore it or commit the deletion to git.",
    },
  
    // Sidebar (app shell),

  importExport: {
      kindWorkspace: "Workspace",
      kindRequests: "Requests",
      kindMocks: "Mocks",
      kindEnvironments: "Environments",
      kindMappings: "Mappings",
      kindProxyRules: "Proxy Rules",
      kindWebsockets: "WebSockets",
      kindWebhooks: "Webhooks",
      descWorkspace: "Export/import entire workspace with all entities",
      descRequests: "Saved HTTP requests and folders",
      descMocks: "Mock response rules and folders",
      descEnvironments: "Environment variable sets",
      descMappings: "Domain-to-target proxy mappings",
      descProxyRules: "URL pattern proxy rules",
      descWebsockets: "WebSocket connection definitions",
      descWebhooks: "Webhook endpoint definitions",
      exportData: "Export Data",
      importData: "Import Data",
      exporting: "Exporting…",
      importing: "Importing…",
      exportComplete: "Export complete.",
      exportFailed: "Export failed.",
      importFailed: "Import failed.",
      couldNotReadFile: "Could not read file.",
      importedItems: "Imported {n} item{s}",
      skippedSuffix: ", skipped {n}",
      whatToWorkWith: "What would you like to work with?",
      chooseExportFormatFor: "Choose export format for",
      chooseImportFormatFor: "Choose import format for",
      noFormatsAvailable: "No formats available.",
      back: "Back",
      exportEllipsis: "Export…",
      chooseFile: "Choose File…",
      collisionSummary: "{count} of {total} items have matching IDs in this workspace.",
      howConflictsHandled: "How should conflicts be handled?",
      import: "Import",
      collisionKeepLabel: "Keep existing",
      collisionOverrideLabel: "Override with imported",
      collisionNewLabel: "Import as new copies",
      collisionKeepDesc: "Conflicting items are skipped; only new items are imported.",
      collisionOverrideDesc: "Imported items replace the existing ones with the same ID.",
      collisionNewDesc: "All imported items get new IDs — no conflicts.",
    },
  
    // Global footer (sync status),
} as const;
