export const workspaceStrings = {
  workspace: {
      title: "Workspace",
      subtitle: "Configure workspace settings and remote sync",
      helpText: "Manage workspace name and connect to a remote Git repository for syncing across machines. Connecting pushes local data to an empty remote, or clones an existing remote into an empty workspace.",
      sectionDetails: "Details",
      sectionSync: "Remote Sync",
      sectionData: "Data",
      sectionDanger: "Danger Zone",
      workspaceName: "Workspace Name",
      workspaceCreated: "Created",
      remoteUrl: "Remote URL",
      remoteUrlDesc: "Git repository URL. Cannot be changed once connected.",
      remoteUrlPlaceholder: "https://github.com/you/workspace-data.git",
      branch: "Branch",
      branchPlaceholder: "main",
      autoSync: "Auto-sync",
      autoSyncDesc: "Automatically push after changes and pull every 30 seconds.",
      connectBtn: "Connect",
      connectingBtn: "Connecting…",
      disconnectBtn: "Disconnect",
      pushBtn: "Push",
      pullBtn: "Pull",
      pushingBtn: "Pushing…",
      pullingBtn: "Pulling…",
      lastPushed: "Last pushed",
      lastPulled: "Last pulled",
      never: "never",
      statusIdle: "Synced",
      statusPushing: "Pushing…",
      statusPulling: "Pulling…",
      statusCloning: "Connecting…",
      statusError: "Error",
      exportBtn: "Export Workspace…",
      exportDesc: "Save this workspace's data to a JSON file.",
      importBtn: "Import Into Workspace…",
      importDesc: "Replace this workspace's data from a previously exported JSON file.",
      deleteBtn: "Delete Workspace",
      deleteDesc: "Permanently delete this workspace and all its data.",
      deleteConfirm: "This will permanently delete \"{name}\" and all its data. Are you sure?",
      deleteConfirmBtn: "Delete",
      connectWarningNonEmpty: "Your local data will be pushed to the remote. The remote must be empty.",
      connectWarningEmpty: "The remote repository will be cloned into this workspace. Continue?",
      confirmConnect: "Connect",
      cancelConnect: "Cancel",
      syncError: "Sync error",
      disconnectWarning: "Disconnect from remote? Local data is preserved.",
      disconnectConfirm: "Disconnect",
      imported: "Workspace imported",
      exported: "Workspace exported",
      importFailed: "Import failed",
      exportFailed: "Export failed",
    },

  runner: {
      title: "Runner",
      helpText: "Run scripts and commands. Add shell scripts, commands, Node.js, Python, Docker and more.",
      addRunner: "Add Runner",
      newRunner: "New Runner",
      noTitle: "No runners configured",
      noDesc: "Add runners to execute scripts and commands from here.",
      searchPlaceholder: "Search runners…",
      drafts: "Drafts",
      collapseSidebar: "Collapse sidebar",
      labelName: "Name",
      labelType: "Type",
      labelWorkingDirectory: "Working Directory",
      labelCommand: "Command",
      labelScriptPath: "Script Path",
      labelScriptName: "Script Name",
      labelPackageManager: "Package Manager",
      labelTarget: "Script / Module",
      labelMode: "Mode",
      labelNodeFlags: "Node Flags",
      labelImage: "Docker Image",
      labelPorts: "Port Mappings",
      labelVolumes: "Volumes",
      labelDockerfile: "Dockerfile",
      labelComposeFile: "Compose File",
      labelServices: "Services",
      labelExtraArgs: "Extra Arguments",
      labelArguments: "Arguments",
      labelPreRunCommand: "Pre-Run Command",
      browse: "Browse",
      browseFile: "Browse for file",
      browseFolder: "Browse for folder",
      hintRequired: "required",
      hintOptional: "optional",
      hintCommand: "command to run, e.g. npm run dev",
      hintPreRunCommand: "runs in working directory before start",
      hintScriptName: "from package.json scripts",
      hintNodeFlags: "optional — e.g. --experimental-modules",
      hintPortMappings: "host:container, one per line",
      hintVolumes: "host:container, one per line",
      hintServices: "optional — space-separated service names",
      hintExtraArgs: "additional arguments",
      statusRunning: "Running",
      statusStarting: "Starting…",
      statusStopping: "Stopping…",
      statusError: "Error",
      statusExited: "Exited",
      statusIdle: "Idle",
      actionRun: "Run",
      actionStop: "Stop",
      actionRestart: "Restart",
      runAll: "Run All",
      stopAll: "Stop All",
      terminalNoOutput: "No output yet — start the runner to see output",
      confirmDelete: "Delete this runner? This cannot be undone.",
      filterShellScripts: "Shell Scripts",
      filterBatchFiles: "Batch Files",
      filterPowerShell: "PowerShell",
      filterJavaScript: "JavaScript",
      filterPythonFiles: "Python Files",
      filterDockerfile: "Dockerfile",
      filterComposeFiles: "Compose Files",
      filterAllFiles: "All Files",
      modeScript: "Script",
      modeModule: "Module (-m)",
      modeImage: "Pull Image",
      modeBuild: "Build & Run",
      saveRunner: "Save Runner",
      cancelEdit: "Cancel",
      editConfig: "Edit Config",
      configHidden: "Config",
      configExpand: "Show config",
      configCollapse: "Hide config",
    },
  
    // Import/export,

  collectionRunner: {
      requestCount: "{count} request{s}",
      requestsHeader: "Requests",
      requests: "requests",
      tests: "tests",
      failed: "failed",
      delay: "Delay",
      ms: "ms",
      run: "Run",
      runAgain: "Run Again",
      running: "Running...",
      allPassed: "All passed",
      someFailed: "Some failed",
      exportTitle: "Export report as HTML or JSON",
      dragToReorder: "- drag to reorder",
      noRequests: "No requests in this folder.",
      untitled: "Untitled",
      pressRunPrefix: "Press",
      pressRunSuffix: "to execute all requests in this collection.",
      error: "Error",
      preScriptLabel: "Pre-script:",
      postScriptLabel: "Post-script:",
      console: "Console",
    },
  
    // Webhooks panel,

  healthBar: {
      title: "Health Bar",
      service: "service",
      services: "services",
      notChecked: "Not checked",
      checking: "Checking…",
      error: "Error",
      unknown: "Unknown",
      viewLastResponse: "View last response",
      lastChecked: "Last checked",
      autoRefresh: "Auto refresh",
      refreshService: "Refresh this service",
      removeService: "Remove service",
      refreshAll: "Refresh All",
      addService: "Add Service",
      editService: "Edit Service",
      serviceName: "Service Name",
      healthCheckUrl: "Health Check URL",
      supportsEnvVars: "Supports environment variables:",
      nameRequired: "Name is required",
      urlRequired: "Health check URL is required",
      urlInvalid: "Enter a valid URL (e.g. http://localhost:3000/health)",
      update: "Update",
      publish: "Publish",
      publishing: "Publishing…",
      synced: "Health Bar is synced",
      loadingServices: "Loading services…",
      noServices: "No services added",
      noServicesDesc: "Add a service to start monitoring its health check endpoint.",
    },
  
    // Logs panel,

  logs: {
      title: "Logs",
      subtitle: "HTTP traffic through the app — via proxy or RFC 6761",
      searchPlaceholder: "URL, method, host…",
      resume: "Resume",
      pause: "Pause",
      clear: "Clear",
      noEntries: "No log entries",
      emptyHint: "HTTP traffic will appear here as requests pass through the app.",
      noMatch: "No entries match your search.",
      colTime: "Time",
      colMethod: "Mth",
      colStatus: "St",
      colUrl: "URL",
      colVia: "Via",
      colDur: "Dur",
      replay: "Replay",
      replayTitle: "Replay this request",
      mock: "Mock",
      mockTitle: "Create mock from this request",
      entries: "entries",
      shown: "shown",
      paused: "paused",
      footerNote: "newest first · last {max} kept · auto-cleared when full",
    },
  
    // Audit log panel,

  auditLog: {
      title: "Audit Log",
      subtitle: "Every configuration change in this workspace —",
      entries: "entries",
      loading: "Loading…",
      noEntries: "No audit entries found.",
      loadingDiff: "Loading diff…",
      noSnapshot: "No snapshot data available.",
      entityDeleted: "Entity was deleted.",
      beforeStateStored: "Before state stored in git history.",
      entityCreated: "Entity was created — no prior state.",
      noFieldChanges: "No field changes detected.",
      allEntities: "All entities",
      entityMock: "Mock",
      entityMapping: "Mapping",
      entityRule: "Proxy Rule",
      entityEnvironment: "Environment",
      entityRequest: "Request",
      entityWebSocket: "WebSocket",
      entityFolder: "Folder",
      entityWorkspace: "Workspace",
      allActions: "All actions",
      actionCreate: "Create",
      actionUpdate: "Update",
      actionDelete: "Delete",
    },
  
    // Folder tree (sidebar),
} as const;
