/**
 * `runner.saveReport` — the one `runner.*` command in the step-3b inventory that can move as-is.
 *
 * ## Why this one moves and its two siblings do not
 *
 * `runner.saveConfig` / `runner.loadConfig` are `BLOCKED` by the frozen protocol: `RunnerConfigSchema`
 * requires `requestOrder`, while `tests/integration/runnerStorage.integration.test.ts` saves
 * `{delayMs, stopOnFailure, iterations}` and asserts an exact round-trip. That is a *passing test* as
 * evidence, and the ratchet in `tests/ipc/handlers.test.ts` asserts the block directly so widening the
 * schema later fails loudly instead of leaving these filed as "unimplemented" forever.
 *
 * `runner.exportReport` had already moved (P2/P3), so this file completes the runner's request paths.
 *
 * ## The move is safe, and the reason is worth recording
 *
 * `RunReport` is a plain `z.object()`, and zod's `z.object()` **strips unknown keys**. So the
 * interesting question is not "does the schema accept the payload" — a permissive-enough schema
 * accepting a report is not the same as it *preserving* one — but **"does parsing lose any field the
 * renderer sends?"**. It does not, and that was checked rather than assumed:
 *
 * | Type | Fields | In `RunReport`? |
 * | --- | --- | --- |
 * | `CollectionRunReport` (`renderer/lib/collectionRunner.ts`) | 9 | all 9 |
 * | `RunnerRequestResult` | 11 | all 11 |
 *
 * That table is the whole reason this is `MOVABLE` rather than `NARROWED`. The P1 schema was written
 * from the HTML renderer's field *usage*, which is why it dropped `requestId` / `url` / `testLogs` /
 * `preScriptError` / `postScriptError`; P3 widened `RunResult` to add them back precisely because
 * `z.object()` strips silently and the HTML renderer would not have noticed. A report truncated here
 * would be a data-loss bug in saved run history, not a type error.
 *
 * ## Why the HTML is rendered here rather than in the shell
 *
 * `renderRunnerHtml` lives in `packages/engine/src/runner/reportHtml.ts` because it is a generated
 * artifact and `runner.exportReport` — already routed through the registry — needs the same renderer.
 * Writing `report.html` next to `report.json` is what the shell body did, and it stays.
 *
 * ## The trap: do NOT re-point the legacy channel at this module yet
 *
 * The obvious "DRY" follow-up is to replace the shell's `runner:saveReport` body with
 * `commandRegistry.invoke("runner.saveReport", params, ctx)`. **That was tried in `serverCommands.ts`
 * and reverted, and it is a real regression rather than a style question.**
 *
 * The reason is how this module gets registered. `config.get` / `env.setActive` / `workspace.setActive`
 * are registered at **module scope** in `coreHandlers.ts`, so importing that file populates them. This
 * module is registered by an **explicit call inside `registerIpcHandlers()`**, so a legacy body that
 * delegates here acquires a hidden ordering dependency on a function callers are not obliged to run —
 * and two suites already register handler *groups* without it. The failure is a `No handler registered`
 * at *invocation* time, so nothing catches it at build time and the shell's own handler file looks
 * untouched.
 *
 * So the duplication is deliberate and bounded. **Step 3** removes it by deleting
 * `registerIpcHandlers()` and the shell's handler groups together — one implementation, no second
 * entry point to keep in sync.
 */
import * as fs from "fs";
import * as path from "path";
import type { RunnerSaveReportParams } from "@bifurc/protocol";
import type { CommandRegistry } from "../commands/registry";
import { wsDir } from "../store/workspaceFs";
import { renderRunnerHtml } from "./reportHtml";

export function registerRunnerCommands(registry: CommandRegistry): void {
    registry.register("runner.saveReport", (params: RunnerSaveReportParams) => {
        try {
            const folderId = params.report.folderId;
            const ts = params.report.startedAt;
            const runDir = path.join(
                wsDir(params.workspaceId),
                "requests",
                ".runs",
                folderId,
                String(ts),
            );
            fs.mkdirSync(runDir, { recursive: true });
            fs.writeFileSync(
                path.join(runDir, "report.json"),
                JSON.stringify(params.report, null, 2),
                "utf-8",
            );

            // The HTML is generated by the engine, because `runner.exportReport` needs the same
            // renderer and a second copy would drift.
            const html = renderRunnerHtml(params.report);
            fs.writeFileSync(path.join(runDir, "report.html"), html, "utf-8");
            return { ok: true };
        } catch (err) {
            // Resolved, not thrown: the renderer branches on `{ok:false}`, and a throw would surface
            // as an `EngineError` with the message flattened — losing the `ok` flag entirely.
            return { ok: false, error: (err as Error)?.message ?? "Failed to save report" };
        }
    });
}
