export const protocolsStrings = {
  graphql: {
      requestTitle: "GRAPHQL REQUEST",
      mockTitle: "GRAPHQL MOCK",
      requestNamePlaceholder: "Request name…",
      mockNamePlaceholder: "Mock name…",
      methodPost: "POST",
      endpoint: "ENDPOINT",
      sending: "Sending",
      regex: "Regex",
      tabQuery: "Query",
      tabVariables: "Variables",
      tabHeaders: "Headers",
      tabPreScript: "Pre-Script",
      tabPostScript: "Post-Script",
      tabSchema: "Schema",
      tabMatch: "Match",
      tabResponseHeaders: "Response Headers",
      operationType: "Operation Type",
      opAny: "Any",
      opQuery: "Query",
      opMutation: "Mutation",
      opSubscription: "Subscription",
      operationName: "Operation Name",
      operationNamePlaceholder: "Match operation name (leave empty to match all)",
      responseStatus: "Response Status",
      responseDelay: "Response Delay (ms)",
      response: "Response",
      responseBody: "Response Body",
      responsePlaceholder: "Send a request to see the response…",
      update: "Update",
      schema: "Schema",
      back: "Back",
      introspect: "+ Introspect",
      introspecting: "Introspecting…",
      fetchSchema: "Fetch Schema",
      introspectionFailed: "Introspection failed",
      networkError: "Network error",
      selectSchema: "Select schema…",
      filterOperations: "Filter operations…",
      noSchemasLoaded: "No schemas loaded. Click \"Introspect\" to fetch a schema from a GraphQL endpoint.",
      noOperationsInSchema: "No operations found in schema.",
      insertQueryTemplate: "Insert {name} query template",
      deleteMockConfirm: "Delete this mock? This cannot be undone.",
      deleteRequestConfirm: "Delete this request? This cannot be undone.",
      copySuffix: "{name} (copy)",
      untitled: "Untitled",
      newMockTab: "New GraphQL Mock",
      newRequestTab: "New GraphQL Request",
      newMockTabTitle: "New GraphQL mock",
      newRequestTabTitle: "New GraphQL request",
      closeTab: "Close tab",
      drafts: "Drafts",
      searchMocks: "Search mocks…",
      searchRequests: "Search requests…",
      collapseSidebar: "Collapse sidebar",
      expandSidebar: "Expand sidebar",
      noMocksOpen: "No GraphQL mocks open",
      noMocksOpenHintBefore: "Mock GraphQL operations by matching query names and types. Click",
      noMocksOpenHintAfter: "to create your first mock.",
      noRequestsOpen: "No GraphQL requests open",
      noRequestsOpenHint: "Send GraphQL queries and mutations. Import a schema or use server introspection to get started.",
      mockCount: "{count} mocks",
      requestCount: "{count} requests",
    },
  
    // gRPC tabs & panels,

  grpc: {
      requestTitle: "gRPC Request",
      mockTitle: "gRPC Mock",
      requestNamePlaceholder: "Request name…",
      mockNamePlaceholder: "Mock name…",
      sending: "Sending…",
      streamUnary: "Unary",
      streamServer: "Server Stream",
      streamClient: "Client Stream",
      streamBidi: "Bidi Stream",
      streamBidirectional: "Bidirectional",
      streamServerStreaming: "Server Streaming",
      streamClientStreaming: "Client Streaming",
      type: "Type:",
      useReflection: "Use Reflection",
      enabled: "Enabled",
      tabMessage: "Message",
      tabMetadata: "Metadata",
      tabPreScript: "Pre-Script",
      tabPostScript: "Post-Script",
      tabProto: "Proto",
      tabResponse: "Response",
      tabTrailingMetadata: "Trailing Metadata",
      tabResponseBody: "Response Body",
      tabResponseMetadata: "Response Metadata",
      tabSettings: "Settings",
      noMetadata: "No metadata. Add key-value pairs for gRPC metadata.",
      noResponseMetadata: "No response metadata.",
      responseDelay: "Response Delay (ms)",
      errorCode: "Error Code (0 = no error)",
      errorMessage: "Error Message",
      errorMessagePlaceholder: "Optional error message",
      status: "Status:",
      noResponseYet: "No response yet. Send a request to see results.",
      responseNumber: "Response #{n}",
      noTrailingMetadata: "No trailing metadata received.",
      update: "Update",
      unknownError: "Unknown error",
      sendFailed: "Send failed",
      reflectionFailed: "Reflection failed",
      connectionFailed: "Connection failed",
      proto: "Proto",
      back: "Back",
      import: "+ Import",
      importProtoFile: "Import .proto File",
      or: "OR",
      reflecting: "Reflecting…",
      serverReflection: "Server Reflection",
      selectProtoFile: "Select proto file…",
      filterMethods: "Filter methods…",
      noProtoFiles: "No proto files loaded. Click \"Import\" to add a .proto file or use server reflection.",
      selectMethod: "Select {service}/{method}",
      deleteMockConfirm: "Delete this mock? This cannot be undone.",
      deleteRequestConfirm: "Delete this request? This cannot be undone.",
      copySuffix: "{name} (copy)",
      newMockTab: "New gRPC Mock",
      newRequestTab: "New gRPC Request",
      newMockTabTitle: "New gRPC mock",
      newRequestTabTitle: "New gRPC request",
      closeTab: "Close tab",
      mockLabel: "gRPC Mock",
      requestLabel: "gRPC Request",
      unnamed: "Unnamed",
      drafts: "Drafts",
      searchMocks: "Search gRPC mocks…",
      searchRequests: "Search gRPC requests…",
      collapseSidebar: "Collapse sidebar",
      expandSidebar: "Expand sidebar",
      stopMockServer: "Stop gRPC mock server",
      startMockServer: "Start gRPC mock server",
      mockServerRunning: "Mock server :{port}",
      mockServerStopped: "Mock server stopped",
      noMocksOpen: "No gRPC mocks open",
      noMocksOpenHint: "Run a local gRPC mock server. Import proto definitions to register service methods and configure responses.",
      noRequestsOpen: "No gRPC requests open",
      noRequestsOpenHint: "Make gRPC calls. Import a .proto file or use server reflection to discover available methods.",
      mockCount: "{count} mocks",
      requestCount: "{count} requests",
    },
  
    // SOAP tabs & panels,

  soap: {
      requestTitle: "SOAP Request",
      mockTitle: "SOAP Mock",
      requestNamePlaceholder: "Untitled Request",
      mockNamePlaceholder: "Untitled Mock",
      methodPost: "POST",
      sending: "Sending",
      soapAction: "SOAPAction:",
      endpointPattern: "Endpoint Pattern:",
      soapActionMatch: "SOAPAction Match:",
      responseStatus: "Response Status:",
      delay: "Delay (ms):",
      regex: "Regex",
      tabBody: "Body",
      tabHeaders: "Headers",
      tabPreScript: "Pre-Script",
      tabPostScript: "Post-Script",
      tabWsdl: "WSDL",
      tabResponseBody: "Response Body",
      tabResponseHeaders: "Response Headers",
      noResponseYet: "No response yet",
      update: "Update",
      requestFailed: "Request failed",
      wsdl: "WSDL",
      back: "Back",
      fetchWsdl: "+ Fetch WSDL",
      fetching: "Fetching…",
      fetchAndImport: "Fetch & Import",
      fetchWsdlFailed: "Failed to fetch WSDL",
      networkError: "Network error",
      selectWsdl: "Select WSDL…",
      filterOperations: "Filter operations…",
      noWsdlsImported: "No WSDLs imported. Click \"Fetch WSDL\" to import a WSDL from a URL.",
      noOperationsInWsdl: "No operations found in WSDL.",
      insertEnvelope: "Insert {name} SOAP envelope",
      deleteMockConfirm: "Delete this mock? This cannot be undone.",
      deleteRequestConfirm: "Delete this request? This cannot be undone.",
      copySuffix: "{name} (copy)",
      newMockTab: "New SOAP Mock",
      newRequestTab: "New SOAP Request",
      newMockTabTitle: "New SOAP mock",
      newRequestTabTitle: "New SOAP request",
      closeTab: "Close tab",
      mockLabel: "SOAP Mock",
      requestLabel: "SOAP Request",
      drafts: "Drafts",
      searchMocks: "Search SOAP mocks…",
      searchRequests: "Search SOAP requests…",
      collapseSidebar: "Collapse sidebar",
      expandSidebar: "Expand sidebar",
      noMocksOpen: "No SOAP mocks open",
      noMocksOpenHintBefore: "Mock SOAP services by matching SOAPAction headers and operation names. Click",
      noMocksOpenHintAfter: "to create your first mock.",
      noRequestsOpen: "No SOAP requests open",
      noRequestsOpenHint: "Send SOAP requests. Import a WSDL to discover available operations and auto-generate envelopes.",
      mockCount: "{count} mocks",
      requestCount: "{count} requests",
    },
  
    // Collection runner,
} as const;
